# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** ⚙️ **Bản LOCAL** — Jupyter Lab/Notebook local (Python 3.10+) + Neo4j AuraDB/local, dùng file `.env` thay cho Colab Secrets. (Bản gốc chạy trên Colab: `Day19_GraphRAG_vs_FlatRAG_Production_Lab_Guide.ipynb`)  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 1200` (hub-stratified: ưu tiên chunk nhắc Microsoft/Google/Amazon/…)

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.
Local fix notes: Entity Resolution dùng `threshold≈0.85` + lexical guard chặt hơn để có đủ `MERGE_MANUAL` / `MERGE_VECTOR` / `REJECT_GUARD`; Super-node production threshold vẫn `degree > 100`, kèm lab stress-demo khi đồ thị còn nhỏ.

### Secrets — chạy LOCAL bằng file `.env`
Đây là bản đã chỉnh để chạy trên máy local (Jupyter Lab/Notebook), không dùng Colab Secrets.

Các bước:
1. `pip install -r requirements.txt` (đã gồm `python-dotenv`).
2. `cp .env.example .env` rồi điền các giá trị thật vào `.env`.
3. Notebook sẽ tự nạp `.env` qua `python-dotenv` ở cell 1.2 — không cần Colab Secrets.

Biến cần khai báo trong `.env`:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`, `NEO4J_DATABASE`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

**Không hard-code API key vào notebook nộp bài** — `.env` đã nằm trong `.gitignore`, không bị commit lên GitHub.

In [1]:
#@title 1.1 — Install (auto-skip nếu chạy local đã `pip install -r requirements.txt`)
import sys

IN_COLAB = "google.colab" in sys.modules

if IN_COLAB:
    %pip -q install neo4j pandas numpy pyarrow sentence-transformers faiss-cpu groq openai tqdm networkx datasets python-dotenv
else:
    print(
        "Local run: dependencies nên được cài trước bằng:\n"
        "    pip install -r requirements.txt\n"
        "Bỏ qua %pip install trong notebook để tránh cài lại/conflict môi trường local."
    )


Local run: dependencies nên được cài trước bằng:
    pip install -r requirements.txt
Bỏ qua %pip install trong notebook để tránh cài lại/conflict môi trường local.


In [33]:
#@title 1.2 — Imports & config
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import faiss

# --- LOCAL RUN: nạp biến môi trường từ .env (bỏ qua nếu không có file .env / không cài dotenv) ---
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("[Cảnh báo] python-dotenv chưa cài — chạy `pip install python-dotenv` hoặc set biến môi trường thủ công.")

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def get_secret(name, default=None):
    # Local run: ưu tiên biến môi trường (nạp từ .env ở trên).
    # Nếu chạy lại trên Colab, fallback sang Colab Secrets khi biến chưa có trong os.environ.
    value = os.environ.get(name)
    if value is not None:
        return value
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value
    except Exception:
        pass
    return default

NEO4J_URI = get_secret("NEO4J_URI", "")
NEO4J_USER = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "neo4j")

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")
GROQ_MODEL = get_secret("GROQ_MODEL", "")

JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")

# NER+RE extraction (cell 2.1): openai | groq
EXTRACT_PROVIDER = get_secret("EXTRACT_PROVIDER", "openai").lower()
EXTRACT_MODEL = get_secret("EXTRACT_MODEL", "gpt-4o-mini")

# Answer generation + seed extraction (cell 3.2, 3.4, 4.3): openai | groq
GENERATE_PROVIDER = get_secret("GENERATE_PROVIDER", EXTRACT_PROVIDER).lower()
GENERATE_MODEL = get_secret("GENERATE_MODEL", EXTRACT_MODEL)

HF_TOKEN = get_secret("HF_TOKEN", "")

# LOCAL RUN: dữ liệu lưu trong thư mục dự án thay vì /content (Colab)
os.makedirs("data", exist_ok=True)
os.makedirs("outputs", exist_ok=True)
DATA_PATH = "data/hackernoon_subset.csv"
LAB_MAX_ARTICLES = 1500
LAB_MAX_CHUNKS = 3000
# Tăng extract + stratify hub để densify graph (super-node) và tăng biến thể entity (ER audit).
EXTRACTION_MAX_CHUNKS = 1200
EXTRACTION_HUB_RATIO = 0.70
CHUNK_WORDS = 220
CHUNK_OVERLAP_WORDS = 40

# Entity Resolution knobs (rubric 2.3)
ENTITY_SIM_THRESHOLD = 0.85
MERGE_GUARD_RATIO = 0.78
ENTITY_ANN_TOP_K = 8

# Super-node: production policy (rubric 2.1) + lab stress-demo khi graph còn nhỏ
SUPER_NODE_DEGREE = 100
SUPER_NODE_EDGE_CAP = 50
LAB_SUPERNODE_STRESS_DEGREE = 10

HUB_KEYWORDS = [
    "microsoft", "google", "amazon", "apple", "meta", "openai",
    "nvidia", "ibm", "oracle", "salesforce", "servicenow", "amd",
    "intel", "anthropic", "cohere", "hugging face", "aws", "azure",
]

## 1.3 — Download HackerNoon Dataset bằng Hugging Face Streaming

Cell dưới đây stream trực tiếp dataset **`HackerNoon/tech-company-news-data-dump`** và ghi dần ra CSV, nên không cần tải toàn bộ dataset vào RAM.

### Hai cơ chế giới hạn

- `LIMIT_ROWS`: số dòng tối đa.
- `LIMIT_MB`: dung lượng file tối đa.
- `PRIORITIZE_MB = True`: ưu tiên dừng theo dung lượng MB.
- `PRIORITIZE_MB = False`: thanh tiến trình theo số dòng, nhưng **vẫn giữ hard-stop `LIMIT_ROWS`**.

### Lưu ý

- Đặt `HF_TOKEN` trong file `.env` (local) hoặc **Colab Secrets** (nếu chạy trên Colab). Không hard-code token vào notebook.
- Nếu dataset yêu cầu quyền truy cập/gated access, hãy mở trang dataset trên Hugging Face và hoàn tất bước **Agree/Request access** trước.
- Sau khi cell hoàn tất, `DATA_PATH` mặc định đã trỏ tới `data/hackernoon_subset.csv` (thư mục `data/` trong repo), nên cell loader kế tiếp có thể chạy trực tiếp.

In [3]:
#@title 1.3 — Stream HackerNoon dataset -> CSV
import csv
import os
from datasets import load_dataset
from tqdm.auto import tqdm

DATASET_NAME = "HackerNoon/tech-company-news-data-dump"
# LOCAL RUN: ghi vào thư mục data/ trong repo thay vì /content (Colab)
os.makedirs("data", exist_ok=True)
OUTPUT_CSV = "data/hackernoon_subset.csv"

# Giới hạn cho bản lab. Có thể tăng sau buổi học.
# LIMIT_ROWS = 1_000_000
LIMIT_ROWS = 10_000
LIMIT_MB = 300

# True  -> progress/dừng ưu tiên theo MB
# False -> progress theo rows; vẫn có hard-stop LIMIT_ROWS
PRIORITIZE_MB = True

# Đọc từ .env (local) hoặc Colab Secrets qua get_secret() ở cell config.
if not HF_TOKEN:
    raise ValueError(
        "Thiếu HF_TOKEN. Hãy thêm Hugging Face Access Token vào file .env (biến HF_TOKEN=hf_...) "
        "hoặc Colab Secrets nếu chạy trên Colab."
    )

print("Đang kết nối luồng dữ liệu (streaming)...")

try:
    dataset = load_dataset(
        DATASET_NAME,
        split="train",
        streaming=True,
        token=HF_TOKEN,
    )
    iterator = iter(dataset)

    first_row = next(iterator)
    headers = list(first_row.keys())

    print(f"Đang ghi dữ liệu vào: {OUTPUT_CSV}")

    rows_written = 0
    total_progress = LIMIT_MB if PRIORITIZE_MB else LIMIT_ROWS
    unit_progress = "MB" if PRIORITIZE_MB else "row"

    with open(OUTPUT_CSV, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        writer.writerow(first_row)
        rows_written += 1

        # Flush để kích thước file phản ánh dữ liệu vừa ghi.
        f.flush()
        file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)

        with tqdm(
            total=total_progress,
            desc=f"Đang tải ({unit_progress})",
            unit=unit_progress,
        ) as pbar:
            if PRIORITIZE_MB:
                pbar.n = min(file_size_mb, LIMIT_MB)
                pbar.refresh()
            else:
                pbar.update(1)

            for row in iterator:
                writer.writerow(row)
                rows_written += 1

                # Kiểm tra dung lượng định kỳ để giảm overhead I/O.
                # Khi gần LIMIT_MB, kiểm tra mỗi row để dừng sát ngưỡng hơn.
                should_check_size = (
                    PRIORITIZE_MB
                    and (
                        rows_written % 100 == 0
                        or file_size_mb >= LIMIT_MB * 0.95
                    )
                )

                if should_check_size:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    pbar.n = min(round(file_size_mb, 2), LIMIT_MB)
                    pbar.refresh()
                elif not PRIORITIZE_MB:
                    pbar.update(1)

                # Hard-stop theo MB nếu đang ưu tiên dung lượng.
                if PRIORITIZE_MB and file_size_mb >= LIMIT_MB:
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn dung lượng: "
                        f"{file_size_mb:.2f} MB "
                        f"(Tổng: {rows_written:,} dòng)"
                    )
                    break

                # Hard-stop theo số dòng trong mọi chế độ.
                if rows_written >= LIMIT_ROWS:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn số dòng: "
                        f"{rows_written:,} dòng "
                        f"(Dung lượng: {file_size_mb:.2f} MB)"
                    )
                    break

        f.flush()

    final_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
    print(
        f"✅ Hoàn thành: {os.path.abspath(OUTPUT_CSV)}\n"
        f"   Rows: {rows_written:,}\n"
        f"   Size: {final_size_mb:.2f} MB"
    )

    # Đồng bộ đường dẫn cho cell loader tiếp theo.
    DATA_PATH = OUTPUT_CSV

except StopIteration:
    raise RuntimeError("Dataset stream rỗng: không lấy được dòng đầu tiên.")
except Exception as e:
    print(f"\n❌ Có lỗi xảy ra: {e}")
    print(
        "Kiểm tra: (1) HF_TOKEN, (2) quyền Agree/Access trên Hugging Face, "
        "(3) kết nối mạng của Colab."
    )
    raise

Đang kết nối luồng dữ liệu (streaming)...


'The read operation timed out' thrown while requesting GET https://huggingface.co/datasets/HackerNoon/tech-company-news-data-dump/resolve/cc6144ccce683dcebb6e63f9a50ca084544af1c0/cleanedCompanyNews.csv
Retrying in 1s [Retry 1/5].


Đang ghi dữ liệu vào: data/hackernoon_subset.csv


Đang tải (MB):   2%|▏         | 5.79/300 [00:00<00:14, 20.51MB/s]         


[DỪNG] Đã đạt giới hạn số dòng: 10,000 dòng (Dung lượng: 5.79 MB)
✅ Hoàn thành: d:\AIThucChien\thuchanh\Day19-CaNhan3\Day19-2A202601376-TrinhHoangNam\data\hackernoon_subset.csv
   Rows: 10,000
   Size: 5.79 MB


In [35]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    print("✅ Neo4j connected.")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

connect_neo4j()
setup_graph_schema()

✅ Neo4j connected.
✅ Schema ready.


In [3]:
#@title 1.5 — Loader + exact dedup + chunking
# Bonus Near-Dedup: SimHash + LSH banding (Challenge A)
NEAR_DEDUP_ENABLED = True
NEAR_DEDUP_HAMMING_THRESHOLD = 3   # max bit differences (of 64) to treat as near-duplicate
NEAR_DEDUP_NUM_BANDS = 4             # LSH bands -> candidate pairs only within buckets

def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def _token_features(text):
    words = norm_space(text).lower().split()
    features = set(words)
    for i in range(len(words) - 1):
        features.add(f"{words[i]} {words[i+1]}")
    return features

def simhash64(text):
    v = [0] * 64
    for token in _token_features(text):
        h = int(hashlib.md5(token.encode("utf-8", errors="ignore")).hexdigest(), 16)
        for i in range(64):
            v[i] += 1 if (h >> i) & 1 else -1
    fp = 0
    for i, bit in enumerate(v):
        if bit >= 0:
            fp |= 1 << i
    return fp

def hamming64(a, b):
    return (a ^ b).bit_count()

def _simhash_band_keys(fingerprint, num_bands=4):
    band_size = 64 // num_bands
    mask = (1 << band_size) - 1
    return [(b, (fingerprint >> (b * band_size)) & mask) for b in range(num_bands)]

def near_dedup_simhash_lsh(df, threshold=NEAR_DEDUP_HAMMING_THRESHOLD, num_bands=NEAR_DEDUP_NUM_BANDS):
    """Near-dedup via SimHash + LSH. O(n) hashing + near-linear candidate checks (not O(n²) all-pairs)."""
    if len(df) <= 1:
        return df.copy(), pd.DataFrame(columns=[
            "kept_article_id", "removed_article_id", "hamming_distance",
            "kept_title", "removed_title", "merge_reason",
        ])

    work = df.reset_index(drop=True).copy()
    fingerprints = [
        simhash64(f"{t}\n{x}") for t, x in zip(work["title"], work["text"])
    ]

    # LSH: only compare articles that collide in at least one band.
    buckets = {}
    for idx, fp in enumerate(fingerprints):
        for key in _simhash_band_keys(fp, num_bands):
            buckets.setdefault(key, []).append(idx)

    uf_parent = list(range(len(work)))

    def find(x):
        while uf_parent[x] != x:
            uf_parent[x] = uf_parent[uf_parent[x]]
            x = uf_parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            uf_parent[rb] = ra

    audit_rows = []
    seen_pairs = set()
    for members in buckets.values():
        if len(members) < 2:
            continue
        for i in range(len(members)):
            for j in range(i + 1, len(members)):
                a, b = members[i], members[j]
                pair = (min(a, b), max(a, b))
                if pair in seen_pairs:
                    continue
                seen_pairs.add(pair)
                dist = hamming64(fingerprints[a], fingerprints[b])
                if dist <= threshold:
                    union(a, b)
                    kept_idx, removed_idx = (a, b) if len(work.at[a, "text"]) >= len(work.at[b, "text"]) else (b, a)
                    audit_rows.append({
                        "kept_article_id": work.at[kept_idx, "article_id"],
                        "removed_article_id": work.at[removed_idx, "article_id"],
                        "hamming_distance": dist,
                        "kept_title": work.at[kept_idx, "title"][:120],
                        "removed_title": work.at[removed_idx, "title"][:120],
                        "merge_reason": f"simhash_lsh: hamming<={threshold}",
                    })

    clusters = {}
    for idx in range(len(work)):
        root = find(idx)
        clusters.setdefault(root, []).append(idx)

    keep_indices = []
    for members in clusters.values():
        best = max(members, key=lambda i: (len(work.at[i, "text"]), -i))
        keep_indices.append(best)

    kept = work.iloc[sorted(keep_indices)].reset_index(drop=True)
    audit_df = pd.DataFrame(audit_rows)
    return kept, audit_df

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    # HackerNoon HF dump uses `description` as the main text field (not `body`/`story`).
    text_col = pick_col(raw, ["text", "content", "article", "body", "story", "description"])
    title_col = pick_col(raw, ["title", "headline"], required=False)
    date_col = pick_col(raw, ["published_date", "date", "published_at", "created_at"], required=False)
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid", "url"], required=False)

    df = pd.DataFrame()
    text = raw[text_col].fillna("").map(norm_space)
    title = raw[title_col].fillna("").map(norm_space) if title_col else pd.Series([""] * len(raw), index=raw.index)
    # When only meta description is available, prepend title for richer chunk context.
    if text_col.lower() == "description" and title_col:
        df["text"] = (title + ". " + text).map(norm_space).str.strip(". ")
    else:
        df["text"] = text
    df["title"] = title

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    if NEAR_DEDUP_ENABLED and len(df) > 1:
        before_near = len(df)
        df, near_dedup_audit_df = near_dedup_simhash_lsh(df)
        removed = before_near - len(df)
        print(
            f"Near dedup (SimHash+LSH, hamming<={NEAR_DEDUP_HAMMING_THRESHOLD}): "
            f"{before_near:,} -> {len(df):,} (-{removed:,})"
        )
        if len(near_dedup_audit_df):
            os.makedirs("outputs", exist_ok=True)
            near_dedup_audit_df.to_csv("outputs/near_dedup_audit.csv", index=False)
            print(f"Near-dedup audit: {len(near_dedup_audit_df):,} merged pairs -> outputs/near_dedup_audit.csv")
        else:
            near_dedup_audit_df = pd.DataFrame()
            print("Near-dedup audit: 0 merged pairs (threshold may be strict for this subset).")
    else:
        near_dedup_audit_df = pd.DataFrame()

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df, near_dedup_audit_df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

raw_df = load_news(DATA_PATH)
news_df, near_dedup_audit_df = standardize_news(raw_df)
chunks_df = build_chunks(news_df)
display(chunks_df.head())
if NEAR_DEDUP_ENABLED and len(near_dedup_audit_df):
    display(near_dedup_audit_df.head(10))

Exact dedup: 4,768 -> 4,104
Near dedup (SimHash+LSH, hamming<=3): 4,104 -> 4,098 (-6)
Near-dedup audit: 6 merged pairs -> outputs/near_dedup_audit.csv


Chunking: 100%|██████████| 1500/1500 [00:00<00:00, 45449.63it/s]


,chunk_id,article_id,title,published_date,text
0,https://www.businesswire.com/news/home/20230515005855/en/onsemi-and-Sineng-Electric-Spearhead-the-Development-of-Sus...,https://www.businesswire.com/news/home/20230515005855/en/onsemi-and-Sineng-Electric-Spearhead-the-Development-of-Sus...,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications,2023-05-16,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications. (Nasdaq: ON) a leader in in...
1,https://www.wku.edu/healthinformationmanagement/::c0000,https://www.wku.edu/healthinformationmanagement/,Bachelor of Science in Health Information Management,2023-08-16,Bachelor of Science in Health Information Management. Health information management (HIM) is a diverse yet evolving ...
2,https://www.federalregister.gov/agencies/office-of-government-information-services::c0000,https://www.federalregister.gov/agencies/office-of-government-information-services,Office of Government Information Services,2023-09-27,Office of Government Information Services. We are announcing 2019''s annual Chief FOIA Officers'' Council meeting co...
3,https://www.buffalo.edu/administrative-services/information-for-suppliers.html::c0000,https://www.buffalo.edu/administrative-services/information-for-suppliers.html,Information for Suppliers,2023-07-03,Information for Suppliers. or service that use covered telecommunications equipment or services as a substantial or ...
4,https://www.devdiscourse.com/article/technology/2518545-ceinsys-tech-ltd-a-specialized-gis-mobility-engineering-serv...,https://www.devdiscourse.com/article/technology/2518545-ceinsys-tech-ltd-a-specialized-gis-mobility-engineering-serv...,Ceinsys Tech Ltd: A specialized GIS & Mobility engineering services provider celebrates 25 Years of Enhancing Possib...,2023-07-11,Ceinsys Tech Ltd: A specialized GIS & Mobility engineering services provider celebrates 25 Years of Enhancing Possib...


,kept_article_id,removed_article_id,hamming_distance,kept_title,removed_title,merge_reason
0,https://www.joplinglobe.com/region/national_business/samsung-showcases-groundbreaking-logic-innovations-at-system-ls...,https://www.galvnews.com/news_ap/business/samsung-showcases-groundbreaking-logic-innovations-at-system-lsi-tech-day-...,1,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech Day 2023,Samsung Showcases Groundbreaking Logic Innovations at System LSI Tech Day 2023,simhash_lsh: hamming<=3
1,https://www.businesswireindia.com/esri-signs-agreement-with-malta-providing-access-to-gis-technology-training-83101....,https://www.finanznachrichten.de/nachrichten-2023-02/58332212-esri-signs-agreement-with-malta-providing-access-to-gi...,2,Esri Signs Agreement with Malta Providing Access to GIS Technology Training,Esri Signs Agreement with Malta Providing Access to GIS Technology Training,simhash_lsh: hamming<=3
2,https://www.vanguardngr.com/2023/06/cupp-to-service-chiefs-adopt-technology-strategy-to-tackle-nigerias-security-cha...,https://www.vanguardngr.com/2023/06/cupp-to-new-service-chiefs-adopt-technology-strategy-to-tackle-security-challenges/,1,CUPP to Service Chiefs: Adopt technology strategy to tackle Nigeria’s security challenges,CUPP to New Service Chiefs: Adopt technology strategy to tackle security challenges,simhash_lsh: hamming<=3
3,https://abc7news.com/411-out-of-service-att-customers-landlines/12671256/,https://abc7chicago.com/411-out-of-service-att-customers-landlines/12671256/,3,411 phone number is going out of service for millions of Americans,411 is going out of service for millions of Americans,simhash_lsh: hamming<=3
4,https://www.usnews.com/news/world/articles/2023-05-10/czech-president-ukraine-could-have-our-l-159-jets,https://www.channelnewsasia.com/world/czech-president-ukraine-could-have-our-l-159-jets-3479446,3,Czech President: Ukraine Could Have Our L-159 Jets,Czech president: Ukraine could have our L-159 jets,simhash_lsh: hamming<=3
5,https://www.tmcnet.com/tmcnet/mobile-world-congress/news/2023/02/20/9762825.htm,https://it.tmcnet.com/news/2023/02/20/9762825.htm,3,1Fit Central Asia''s top all-sports unlimited fitness membership app comes to the UK,1Fit Central Asia''s top all-sports unlimited fitness membership app comes to the UK,simhash_lsh: hamming<=3


### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [23]:
#@title 1.6 — LLM wrapper có retry + JSON parsing
from groq import Groq
from openai import OpenAI

groq_client = Groq(api_key=GROQ_API_KEY) if GROQ_API_KEY else None
openai_client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

def parse_json_object(text):
    text = str(text).strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.I)
    text = re.sub(r"\s*```$", "", text)
    a, b = text.find("{"), text.rfind("}")
    if a < 0 or b <= a:
        raise ValueError("No JSON object found.")
    return json.loads(text[a:b+1])

def groq_chat(messages, model=None, json_mode=False, max_retries=4):
    if groq_client is None:
        raise RuntimeError("Thiếu GROQ_API_KEY.")
    model = model or GROQ_MODEL
    if not model:
        raise RuntimeError("Thiếu GROQ_MODEL.")

    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {
                "model": model,
                "messages": messages,
                "temperature": 0.0,
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            resp = groq_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {
                    "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                    "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                    "total_tokens": getattr(resp.usage, "total_tokens", None),
                }
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            if attempt == max_retries - 1:
                break
            time.sleep(min(20, 2**attempt + random.random()))
    raise RuntimeError(last)

def openai_chat(messages, model=None, json_mode=False, max_retries=6):
    if openai_client is None:
        raise RuntimeError("Thiếu OPENAI_API_KEY.")
    model = model or EXTRACT_MODEL or JUDGE_MODEL or "gpt-4o-mini"
    if not model:
        raise RuntimeError("Thiếu model OpenAI (EXTRACT_MODEL hoặc JUDGE_MODEL).")

    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {
                "model": model,
                "messages": messages,
                "temperature": 0.0,
            }
            if json_mode:
                kwargs["response_format"] = {"type": "json_object"}

            resp = openai_client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, "usage", None):
                usage = {
                    "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
                    "completion_tokens": getattr(resp.usage, "completion_tokens", None),
                    "total_tokens": getattr(resp.usage, "total_tokens", None),
                }
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            err = str(e).lower()
            # backoff dài hơn khi rate limit
            if attempt == max_retries - 1:
                break
            wait = min(60, (2 ** attempt) * 2 + random.random())
            if "rate limit" in err or "429" in err:
                wait = min(90, wait * 2)
            time.sleep(wait)
    raise RuntimeError(last)

def groq_json(system, user, model=None):
    text, usage = groq_chat(
        [{"role": "system", "content": system},
         {"role": "user", "content": user}],
        model=model,
        json_mode=True,
    )
    return parse_json_object(text), usage

def openai_json(system, user, model=None):
    text, usage = openai_chat(
        [{"role": "system", "content": system},
         {"role": "user", "content": user}],
        model=model,
        json_mode=True,
    )
    return parse_json_object(text), usage

def llm_json(system, user, provider=None, model=None):
    """Router JSON LLM: provider='openai' | 'groq'."""
    provider = (provider or EXTRACT_PROVIDER or "openai").lower()
    if provider == "openai":
        return openai_json(system, user, model=model or EXTRACT_MODEL)
    if provider == "groq":
        return groq_json(system, user, model=model or GROQ_MODEL)
    raise ValueError("provider must be 'openai' or 'groq'")

def llm_chat(messages, provider=None, model=None, json_mode=False):
    """Router chat LLM cho answer generation (cell 3.4 / 4.3)."""
    provider = (provider or GENERATE_PROVIDER or EXTRACT_PROVIDER or "openai").lower()
    if provider == "openai":
        return openai_chat(
            messages,
            model=model or GENERATE_MODEL or EXTRACT_MODEL,
            json_mode=json_mode,
        )
    if provider == "groq":
        return groq_chat(messages, model=model or GROQ_MODEL, json_mode=json_mode)
    raise ValueError("provider must be 'openai' or 'groq'")

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [36]:
#@title 1.7 — Coreference resolution theo batch
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
Return strict JSON only.
""".strip()

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences.

Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = llm_json(COREF_SYSTEM, prompt, provider=EXTRACT_PROVIDER, model=EXTRACT_MODEL)
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
        })
    return pd.DataFrame(rows), usage

def run_coref(chunks_subset, batch_size=5):
    out = []
    for start in tqdm(range(0, len(chunks_subset), batch_size), desc="Coref"):
        batch = chunks_subset.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception:
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
            })
        out.append(df)
    return pd.concat(out, ignore_index=True)

def select_extraction_chunks(chunks_df, max_chunks=EXTRACTION_MAX_CHUNKS, hub_ratio=EXTRACTION_HUB_RATIO):
    """Hub-stratified sample: ưu tiên chunk nhắc big-tech để tăng alias + hub degree."""
    df = chunks_df.copy()
    hay = df["text"].fillna("").astype(str).str.lower()
    for col in ("title", "company", "url"):
        if col in df.columns:
            hay = hay + " " + df[col].fillna("").astype(str).str.lower()
    pat = "|".join(re.escape(k) for k in HUB_KEYWORDS)
    hub_mask = hay.str.contains(pat, regex=True, na=False)
    hub, other = df[hub_mask], df[~hub_mask]

    n_hub = min(len(hub), int(max_chunks * hub_ratio))
    n_other = min(len(other), max_chunks - n_hub)
    if n_hub + n_other < max_chunks and len(hub) > n_hub:
        n_hub = min(len(hub), max_chunks - n_other)

    parts = []
    if n_hub:
        parts.append(hub.sample(n_hub, random_state=SEED) if len(hub) > n_hub else hub)
    if n_other:
        parts.append(other.sample(n_other, random_state=SEED) if len(other) > n_other else other)

    out = pd.concat(parts).drop_duplicates(subset=["chunk_id"])
    if len(out) > max_chunks:
        out = out.sample(max_chunks, random_state=SEED)
    out = out.sort_index().reset_index(drop=True)
    print(
        f"Extraction chunks selected: {len(out)} "
        f"(hub_available={int(hub_mask.sum())}, hub_selected={n_hub}, other_selected={n_other})"
    )
    return out

extraction_source = select_extraction_chunks(chunks_df)
coref_df = run_coref(extraction_source)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")

Extraction chunks selected: 1194 (hub_available=165, hub_selected=165, other_selected=1035)


Coref: 100%|██████████| 239/239 [34:42<00:00,  8.72s/it]


# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [37]:
#@title 2.1 — NER + RE extraction
EXTRACT_DEBUG = True          # bật log chi tiết khi debug
EXTRACT_LOG_FIRST_N_ERRORS = 5  # in tối đa N lỗi API đầu tiên
EXTRACT_BATCH_SLEEP = 0.5     # giây nghỉ giữa các batch (giảm rate limit OpenAI)

# Dùng OpenAI gpt-4o-mini (đọc từ cell 1.2: EXTRACT_PROVIDER / EXTRACT_MODEL)
# Đổi trong .env: EXTRACT_PROVIDER=openai, EXTRACT_MODEL=gpt-4o-mini

ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

IMPORTANT: copy chunk_id exactly from INPUT (do not shorten or rewrite URLs).

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return llm_json(EXTRACT_SYSTEM, prompt, provider=EXTRACT_PROVIDER, model=EXTRACT_MODEL)

def _parse_relations_from_item(item, meta, stats, triples):
    cid = item.get("chunk_id")
    if cid not in meta:
        stats["skipped_chunk_id"] += 1
        if EXTRACT_DEBUG and len(stats["chunk_id_mismatches"]) < 5:
            stats["chunk_id_mismatches"].append({
                "returned_chunk_id": cid,
                "expected_sample": next(iter(meta.keys()), None),
            })
        return

    for x in item.get("relations", []):
        stats["relations_raw"] += 1
        s, t = norm_space(x.get("source")), norm_space(x.get("target"))
        st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
        if not s or not t:
            stats["skipped_empty_entity"] += 1
            continue
        if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
            stats["skipped_node_type"] += 1
            if EXTRACT_DEBUG and len(stats["bad_schema_samples"]) < 5:
                stats["bad_schema_samples"].append({
                    "chunk_id": cid,
                    "source_type": st,
                    "target_type": tt,
                    "relation": rel,
                })
            continue
        if rel not in ALLOWED_RELATIONS:
            stats["skipped_relation"] += 1
            if EXTRACT_DEBUG and len(stats["bad_relation_samples"]) < 5:
                stats["bad_relation_samples"].append({
                    "chunk_id": cid,
                    "relation": rel,
                })
            continue
        triples.append({
            "source_raw": s,
            "source_type": st,
            "relation": rel,
            "target_raw": t,
            "target_type": tt,
            "source_chunk_id": cid,
            "published_date": meta[cid] or "",
            "evidence": norm_space(x.get("evidence")),
            "confidence": float(x.get("confidence") or 0.0),
        })
        stats["relations_kept"] += 1

def run_extraction(source_df, batch_size=4, debug=EXTRACT_DEBUG):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []
    stats = {
        "chunks_in": len(source_df),
        "batches_total": 0,
        "batches_ok": 0,
        "batches_failed": 0,
        "items_returned": 0,
        "relations_raw": 0,
        "relations_kept": 0,
        "skipped_chunk_id": 0,
        "skipped_empty_entity": 0,
        "skipped_node_type": 0,
        "skipped_relation": 0,
        "chunk_id_mismatches": [],
        "bad_schema_samples": [],
        "bad_relation_samples": [],
        "sample_response": None,
    }

    if debug:
        print(
            f"[NER+RE debug] provider={EXTRACT_PROVIDER!r} model={EXTRACT_MODEL!r} | "
            f"chunks={len(source_df)} | batch_size={batch_size}"
        )

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        stats["batches_total"] += 1
        try:
            obj, _ = extract_batch(batch)
            stats["batches_ok"] += 1
            if stats["sample_response"] is None and debug:
                stats["sample_response"] = obj
        except Exception as e:
            stats["batches_failed"] += 1
            errors.append({
                "start": start,
                "batch_size": len(batch),
                "chunk_ids": batch["chunk_id"].tolist()[:2],
                "error": str(e),
                "error_type": type(e).__name__,
            })
            continue

        stats["items_returned"] += len(obj.get("items", []))
        for item in obj.get("items", []):
            _parse_relations_from_item(item, meta, stats, triples)

        if EXTRACT_BATCH_SLEEP and start + batch_size < len(source_df):
            time.sleep(EXTRACT_BATCH_SLEEP)

    extraction_debug_stats = stats
    if debug:
        _print_extraction_debug(stats, errors)
    return pd.DataFrame(triples), pd.DataFrame(errors), extraction_debug_stats

def _print_extraction_debug(stats, errors):
    print("\n=== NER+RE DEBUG SUMMARY ===")
    print(
        f"batches: ok={stats['batches_ok']}/{stats['batches_total']} | "
        f"failed={stats['batches_failed']}"
    )
    print(
        f"items returned by LLM={stats['items_returned']} | "
        f"relations raw={stats['relations_raw']} | kept={stats['relations_kept']}"
    )
    print(
        "filtered out -> "
        f"chunk_id mismatch={stats['skipped_chunk_id']} | "
        f"empty entity={stats['skipped_empty_entity']} | "
        f"bad node type={stats['skipped_node_type']} | "
        f"bad relation={stats['skipped_relation']}"
    )

    if errors:
        print(f"\nAPI errors: {len(errors)} (showing first {EXTRACT_LOG_FIRST_N_ERRORS})")
        err_df = pd.DataFrame(errors).head(EXTRACT_LOG_FIRST_N_ERRORS)
        display(err_df)
        top = pd.Series([e["error"] for e in errors]).value_counts().head(3)
        print("Top error messages:")
        for msg, cnt in top.items():
            print(f"  [{cnt}x] {msg[:200]}")

    if stats["chunk_id_mismatches"]:
        print("\nchunk_id mismatch samples (LLM trả ID khác INPUT -> bị bỏ):")
        display(pd.DataFrame(stats["chunk_id_mismatches"]))
    if stats["bad_relation_samples"]:
        print("\nRelation không thuộc allowlist:")
        display(pd.DataFrame(stats["bad_relation_samples"]))
    if stats["bad_schema_samples"]:
        print("\nNode type không hợp lệ:")
        display(pd.DataFrame(stats["bad_schema_samples"]))

    if stats["relations_kept"] == 0:
        print("\n⚠️ 0 triples kept — gợi ý kiểm tra:")
        print(f"  1) EXTRACT_PROVIDER={EXTRACT_PROVIDER!r} EXTRACT_MODEL={EXTRACT_MODEL!r}")
        print("  2) extraction_errors_df có rate limit / auth error?")
        print("  3) chunk_id mismatch? (LLM rút gọn URL)")
        print("  4) Text quá ngắn / prompt quá conservative?")
        if stats["sample_response"] is not None:
            print("\nSample JSON từ batch đầu tiên thành công:")
            print(json.dumps(stats["sample_response"], ensure_ascii=False, indent=2)[:2000])

def debug_extraction_one_batch(source_df=None, n=4):
    """Chạy thử 1 batch nhỏ để debug nhanh (không loop 400 chunk)."""
    src = (source_df if source_df is not None else extraction_source).head(n).copy()
    print(f"Debug 1 batch | n={len(src)} | provider={EXTRACT_PROVIDER!r} model={EXTRACT_MODEL!r}")
    triples_df, errors_df, stats = run_extraction(src, batch_size=len(src), debug=True)
    return triples_df, errors_df, stats

raw_triples_df, extraction_errors_df, extraction_debug_stats = run_extraction(extraction_source)
display(raw_triples_df.head())
if len(extraction_errors_df):
    display(extraction_errors_df.head())

[NER+RE debug] provider='openai' model='gpt-4o-mini' | chunks=1194 | batch_size=4


NER+RE: 100%|██████████| 299/299 [21:08<00:00,  4.24s/it]


=== NER+RE DEBUG SUMMARY ===
batches: ok=299/299 | failed=0
items returned by LLM=548 | relations raw=530 | kept=506
filtered out -> chunk_id mismatch=0 | empty entity=0 | bad node type=0 | bad relation=24

Relation không thuộc allowlist:


,chunk_id,relation
0,https://bestmediainfo.com/2023/03/ias-provides-verification-solution-to-amazon-publisher-services-connections-market...,PROVIDED
1,https://www.buffalo.edu/pharmacy-services-partnerships/drug-information.html::c0000,PROVIDES
2,https://www.middlebury.edu/institute/offices-services/information-technology-services::c0000,PROVIDES
3,https://finance.yahoo.com/news/information-services-group-inc-nasdaq-110739974.html::c0000,OWNED_BY
4,https://www.zawya.com/en/business/energy/apicorp-exits-investment-in-oil-services-company-ashtead-technology-eoch4zq...,EXITS_INVESTMENT_IN


,source_raw,source_type,relation,target_raw,target_type,source_chunk_id,published_date,evidence,confidence
0,onsemi,Company,PARTNERED_WITH,Sineng Electric,Company,https://www.businesswire.com/news/home/20230515005855/en/onsemi-and-Sineng-Electric-Spearhead-the-Development-of-Sus...,2023-05-16,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications.,1.0
1,Walt Disney Co.,Company,LEADS,Bob Iger,Person,https://apnews.com/article/disney-disney-subscribers-loss-9b954f969e3c15fc18cd0054e5e7f6dd::c0000,2023-08-10,Walt Disney Co. CEO Bob Iger vowed to make Walt Disney Co.'s streaming services profitable.,1.0
2,Sojern,Company,ACQUIRED,VenueLytics,Company,https://skift.com/2023/07/11/sojern-expands-into-new-hotel-tech-via-acquisition-heres-the-thinking/::c0000,2023-07-11,Sojern has acquired VenueLytics a platform that provides guest management and communications software for independen...,1.0
3,dynaCERT,Company,DEVELOPED,HydraGEN™ Technology,Technology,https://financialpost.com/pmn/business-wire-news-releases-pmn/dynacerts-hydragen-technology-to-be-featured-by-the-ci...,2023-09-18,dynaCERT’s HydraGEN™ Carbon Emission Reduction Technology line of commercial products,1.0
4,Amazon Publisher Services,Company,USES,verification solution,Technology,https://bestmediainfo.com/2023/03/ias-provides-verification-solution-to-amazon-publisher-services-connections-market...,2023-03-29,IAS is now the first verification provider accessible within the APS Connections Marketplace,1.0


## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [38]:
#@title 2.2 — Entity resolution
CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company"}
MANUAL_ALIASES = {
    "msft": "Microsoft",
    "microsoft corp": "Microsoft",
    "microsoft corporation": "Microsoft",
    "microsoft co": "Microsoft",
    "goog": "Google",
    "googl": "Google",
    "google llc": "Google",
    "google inc": "Google",
    "alphabet": "Google",
    "alphabet inc": "Google",
    "meta platforms": "Meta",
    "meta platforms inc": "Meta",
    "facebook": "Meta",
    "facebook inc": "Meta",
    "aapl": "Apple",
    "apple inc": "Apple",
    "apple computer": "Apple",
    "amzn": "Amazon",
    "amazon.com": "Amazon",
    "amazon com": "Amazon",
    "amazon.com inc": "Amazon",
    "aws": "Amazon",
    "amazon web services": "Amazon",
    "ibm corporation": "IBM",
    "international business machines": "IBM",
    "nvda": "NVIDIA",
    "nvidia corporation": "NVIDIA",
    "openai lp": "OpenAI",
}

# Stem → canonical: bắt MERGE_MANUAL khi extract ra "Microsoft Corporation", "Apple Inc", ...
CANONICAL_BRANDS = {
    "microsoft": "Microsoft",
    "google": "Google",
    "alphabet": "Google",
    "apple": "Apple",
    "meta": "Meta",
    "facebook": "Meta",
    "amazon": "Amazon",
    "aws": "Amazon",
    "openai": "OpenAI",
    "nvidia": "NVIDIA",
    "ibm": "IBM",
    "oracle": "Oracle",
    "salesforce": "Salesforce",
    "servicenow": "ServiceNow",
    "amd": "AMD",
    "intel": "Intel",
    "anthropic": "Anthropic",
    "cohere": "Cohere",
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", norm_space(name)).lower()
    s = re.sub(r"[^\w\s\-\.]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)

def merge_guard(a, b, ratio=MERGE_GUARD_RATIO):
    """Lexical guard: vector-similar pairs must still look like the same surface form."""
    na, nb = strip_suffix(a), strip_suffix(b)
    if na == nb:
        return True
    # Token containment with uneven length often = false friends (Apple vs Apple Music)
    ta, tb = set(na.split()), set(nb.split())
    if ta and tb:
        overlap = len(ta & tb) / max(1, min(len(ta), len(tb)))
        if overlap >= 0.5 and abs(len(ta) - len(tb)) >= 1 and SequenceMatcher(None, na, nb).ratio() < 0.92:
            return False
    return SequenceMatcher(None, na, nb).ratio() >= ratio

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

def resolve_manual_canonical(norm):
    if norm in MANUAL_ALIASES:
        return MANUAL_ALIASES[norm]
    stem = strip_suffix(norm)
    if stem in CANONICAL_BRANDS:
        return CANONICAL_BRANDS[stem]
    if stem in MANUAL_ALIASES:
        return MANUAL_ALIASES[stem]
    return None

def build_resolution_map(raw_triples_df, threshold=ENTITY_SIM_THRESHOLD, top_k=ENTITY_ANN_TOP_K):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        canonical = resolve_manual_canonical(norm)
        if not canonical:
            continue
        left = display_name[key]
        # Chỉ ghi MERGE_MANUAL khi form gốc khác canonical (tránh noise identity)
        if norm_entity(left) == norm_entity(canonical) and strip_suffix(norm) == strip_suffix(canonical):
            mapping[key] = canonical
            continue
        mapping[key] = canonical
        audit.append({
            "type": t, "left": left,
            "right": canonical,
            "similarity": 1.0, "decision": "MERGE_MANUAL"
        })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < threshold:
                    continue
                ok = merge_guard(names[i], names[j])
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "decision": "MERGE_VECTOR" if ok else "REJECT_GUARD"
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        if (typ, n) in mapping:
            return mapping[(typ, n)]
        manual = resolve_manual_canonical(n)
        return manual if manual else name

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}")[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

entity_map, entity_resolution_audit_df = build_resolution_map(raw_triples_df)
triples_df = canonicalize_triples(raw_triples_df, entity_map)

print(
    f"ER threshold={ENTITY_SIM_THRESHOLD}, guard_ratio={MERGE_GUARD_RATIO}, "
    f"audit_rows={len(entity_resolution_audit_df)}"
)
if len(entity_resolution_audit_df):
    print(entity_resolution_audit_df.decision.value_counts().to_string())
    entity_resolution_audit_df.to_csv("outputs/entity_resolution_audit.csv", index=False)
    print("Saved -> outputs/entity_resolution_audit.csv")
display(entity_resolution_audit_df.sort_values("similarity", ascending=False).head(20))


Loading weights: 100%|██████████| 103/103 [00:00<00:00, 4648.60it/s]


ER threshold=0.85, guard_ratio=0.78, audit_rows=23
decision
MERGE_MANUAL    12
MERGE_VECTOR     7
REJECT_GUARD     4
Saved -> outputs/entity_resolution_audit.csv


,type,left,right,similarity,decision
0,Company,ServiceNow Inc.,ServiceNow,1.000000,MERGE_MANUAL
1,Technology,AWS,Amazon,1.000000,MERGE_MANUAL
2,Company,Facebook,Meta,1.000000,MERGE_MANUAL
3,Company,Amazon.com,Amazon,1.000000,MERGE_MANUAL
4,Company,Apple Inc,Apple,1.000000,MERGE_MANUAL
5,Company,Meta Platforms,Meta,1.000000,MERGE_MANUAL
6,Company,Microsoft Corp.,Microsoft,1.000000,MERGE_MANUAL
7,Company,IBM Corp.,IBM,1.000000,MERGE_MANUAL
8,Company,Amazon Web Services Inc.,Amazon,1.000000,MERGE_MANUAL
9,Company,Meta Platforms Inc,Meta,1.000000,MERGE_MANUAL


In [39]:
#@title 2.3 — Node table + UNWIND bulk insert
def clear_graph():
    """Xóa graph trước khi re-ingest để tránh cộng dồn degree giả."""
    run_cypher("MATCH (n) DETACH DELETE n")
    print("Cleared Neo4j graph.")

clear_graph()

def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

nodes_df = build_nodes(triples_df)
bulk_insert_nodes(nodes_df)
bulk_insert_edges(triples_df)


Cleared Neo4j graph.


In [40]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()

{'nodes': 785, 'edges': 504, 'invalid_provenance_edges': 0}


,id,name,type,degree
0,fb0f4df56fab164ec48722f0,Microsoft,Company,15
1,0e132222d1315530d6efca52,Google,Company,14
2,773eeb9b7cc008bff365fcdd,OpenAI,Company,12
3,e6c3db5c28c9a15bfafd2e04,Apple,Company,10
4,cc9c6ee3857729e221d3f6de,ServiceNow,Company,10
5,68b3544368862fc263941c8d,Amazon,Company,9
6,6dbfdfc5a4e8df3668a4dac3,Meta,Company,7
7,3669130c05135dd501f33457,technology,Technology,6
8,6d6d3bc05ca32388a48a053b,Truecaller,Company,5
9,1728ebbc40b86a7b0169c353,White House,Company,5


# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [15]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)

Batches: 100%|██████████| 12/12 [00:24<00:00,  2.07s/it]

Flat vectors: 1503


## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [24]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = llm_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""", provider=GENERATE_PROVIDER, model=GENERATE_MODEL)
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])

        if exact:
            matched += exact
            continue

        if entity_match_vectors is None:
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})

    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)

In [41]:
#@title 3.3 — Graph traversal + super-node mitigation
# SUPER_NODE_DEGREE / SUPER_NODE_EDGE_CAP lấy từ cell 1.2 (production policy).
GLOBAL_EDGE_CAP = 250
MAX_GRAPH_CONTEXT_CHARS = 14000

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def recent_edges(node_id, limit):
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e:e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False,
                           supernode_degree=None):
    """supernode_degree=None -> dùng SUPER_NODE_DEGREE (production)."""
    degree_cap = SUPER_NODE_DEGREE if supernode_degree is None else int(supernode_degree)
    seeds = match_seeds(query)
    if not seeds:
        out = {"context":"","edges":pd.DataFrame(),
               "diagnostics":{"reason":"NO_SEED","supernode_events":[]}}
        return out if return_debug else ""

    frontier = deque((x["id"],0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree = node_degree(node_id)
        limit = int(edge_limit)
        if degree > degree_cap:
            limit = min(limit, SUPER_NODE_EDGE_CAP)
            supernode_events.append({
                "node_id": node_id, "degree": degree, "limit": limit,
                "policy_degree": degree_cap,
            })

        for e in recent_edges(node_id, limit):
            key = (e["source_id"],e["relation"],e["target_id"],e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop+1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "matched_seeds": seeds,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
            "policy_degree": degree_cap,
        }
    }
    return out if return_debug else out["context"]


In [25]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = llm_chat(
        [{"role": "system", "content": ANSWER_SYSTEM},
         {"role": "user", "content": prompt}],
        provider=GENERATE_PROVIDER,
        model=GENERATE_MODEL,
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [44]:
#@title 4.1 — 5 câu Golden starter
# LOCAL RUN: golden dataset lưu trong data/ để khớp cấu trúc bài nộp
os.makedirs("data", exist_ok=True)
GOLDEN_PATH = "data/graphrag_golden_50_first5000_detailed.csv"

starter_golden = pd.DataFrame([
    {
        "id":"G01","group":"factoid",
        "question":"Who was the CEO of Hugging Face in 2023?",
        "reference_answer":"Clément Delangue",
        "reference_evidence":"Validate against instructor dump."
    },
    {
        "id":"G02","group":"multi-hop",
        "question":"Which startups were founded by former Microsoft employees and later received investment from Google?",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G03","group":"cross-doc",
        "question":"Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G04","group":"multi-hop",
        "question":"Find a company invested in by a major technology company that also developed a named AI technology; identify both relations and dates.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G05","group":"cross-doc",
        "question":"Identify one technology connected to the same company in at least two news chunks and summarize how the relationship changed over time.",
        "reference_answer":"",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
])

golden_df = pd.read_csv(GOLDEN_PATH) if Path(GOLDEN_PATH).exists() else starter_golden.copy()
display(golden_df)

def validate_golden(df, require_answers=True):
    required = {"id","group","question","reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required-set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id","question"]])
        raise ValueError("Điền reference_answer trước final evaluation.")
    print("✅ Golden Dataset valid.")

,id,group,difficulty,question,reference_answer,reference_evidence,evidence_row_ids_0based,evidence_urls_json,expected_hops,seed_entities,required_relations,adversarial_dimension,gold_reasoning,scoring_notes,source_scope
0,G5000-26,multi-hop,hard,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...,"[2532, 2537]","[""https://www.reuters.com/technology/amazon-has-drawn-thousands-try-its-ai-service-competing-with-microsoft-google-2...",2,"[""Amazon"", ""Cohere""]","[""PROVIDES_ACCESS_TO"", ""DEVELOPED""]",Duplicate coverage + detail union,Merge the duplicate Amazon reports and retain non-conflicting details from each.,Need Cohere plus the customer-service-agent capability; clinical notes is an additional supported detail.,ONLY first 5000 data rows of hackernoon_subset.csv (pandas index 0-4999)
1,G5000-27,cross-doc,hard,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,row 3357 (2023-06-01 13:16:00): 3 Best Cloud Stocks to Buy in June | row 2905 (2023-06-14 08:47:00): Exclusive: Amaz...,"[3357, 2905]","[""https://www.fool.com/investing/2023/06/01/3-best-cloud-stocks-to-buy-in-june/"", ""https://www.reuters.com/technolog...",2,"[""AMD"", ""AWS""]","[""POWERS"", ""CONSIDERING""]",General-to-specific relation trap,Distinguish a general market statement from a specific vendor adoption claim.,Critical: do not infer AWS adopted the new AMD AI chips.,ONLY first 5000 data rows of hackernoon_subset.csv (pandas index 0-4999)
2,G5000-28,multi-hop,hard,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud,[3395],"[""https://www.tmcnet.com/usubmit/2023/08/29/9871484.htm""]",3,"[""Google Cloud"", ""Meta"", ""Technology Innovation Institute"", ""Anthropic""]","[""HOSTS_MODEL_FROM"", ""PREANNOUNCED""]",Multi-entity model/provider mapping,Build separate provider->model mappings rather than a flat list.,All three providers and their models are required.,ONLY first 5000 data rows of hackernoon_subset.csv (pandas index 0-4999)
3,G5000-29,cross-doc,hard,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",row 3380 (2023-07-21 13:01:00): The White House and big tech companies release commitments on managing AI | row 3330...,"[3380, 3330]","[""https://www.wfae.org/united-states-world/united-states-world/2023-07-21/the-white-house-and-big-tech-companies-rel...",2,"[""White House"", ""Google"", ""Meta"", ""OpenAI"", ""IBM"", ""Adobe"", ""Salesforce""]","[""COMMITTED_TO""]",Temporal participant-set expansion,Compare the named participant sets and shared commitment concept over time.,Do not claim the September companies were part of the July seven unless explicitly named.,ONLY first 5000 data rows of hackernoon_subset.csv (pandas index 0-4999)
4,G5000-30,multi-hop,hard,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 3380 (2023-

In [45]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    if not JUDGE_MODEL:
        raise RuntimeError("Thiếu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        return openai_json(system, user, model=JUDGE_MODEL)[0]

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

In [46]:
#@title 4.3 — Evaluation runner + checkpoint
# LOCAL RUN: checkpoint lưu trong outputs/ (thư mục deliverable) thay vì /content (Colab)
os.makedirs("outputs", exist_ok=True)
CHECKPOINT = "outputs/graphrag_eval_checkpoint.csv"
EVAL_SLEEP = 1.0  # giây nghỉ giữa các câu hỏi (tránh rate limit)

def run_evaluation(golden_df):
    print(
        f"[Eval] generate: {GENERATE_PROVIDER}/{GENERATE_MODEL} | "
        f"judge: {JUDGE_PROVIDER}/{JUDGE_MODEL}"
    )
    rows = []
    for q in tqdm(golden_df.itertuples(index=False), total=len(golden_df), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer(q.question, q.reference_answer, graph["answer"], graph["context"])

        rows.append({
            "id":q.id, "group":q.group, "question":q.question,
            "reference_answer":q.reference_answer,
            "flat_answer":flat["answer"], "graph_answer":graph["answer"],
            "flat_comprehensiveness":jf["comprehensiveness"],
            "graph_comprehensiveness":jg["comprehensiveness"],
            "flat_faithfulness":jf["faithfulness"],
            "graph_faithfulness":jg["faithfulness"],
            "flat_multi_hop_reasoning":jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning":jg["multi_hop_reasoning"],
            "flat_latency_s":flat["latency_s"],
            "graph_latency_s":graph["latency_s"],
            "flat_total_tokens":flat.get("total_tokens"),
            "graph_total_tokens":graph.get("total_tokens"),
            "flat_judge_rationale":jf["rationale"],
            "graph_judge_rationale":jg["rationale"],
            "graph_supernode_events":len(
                graph["graph_debug"]["diagnostics"].get("supernode_events",[])
            )
        })
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
        if EVAL_SLEEP:
            time.sleep(EVAL_SLEEP)
    return pd.DataFrame(rows)

validate_golden(golden_df, require_answers=True)
eval_results_df = run_evaluation(golden_df)
display(eval_results_df)

✅ Golden Dataset valid.
[Eval] generate: openai/gpt-4o-mini | judge: openai/gpt-4o-mini


Evaluation: 100%|██████████| 25/25 [05:16<00:00, 12.65s/it]


,id,group,question,reference_answer,flat_answer,graph_answer,flat_comprehensiveness,graph_comprehensiveness,flat_faithfulness,graph_faithfulness,flat_multi_hop_reasoning,graph_multi_hop_reasoning,flat_latency_s,graph_latency_s,flat_total_tokens,graph_total_tokens,flat_judge_rationale,graph_judge_rationale,graph_supernode_events
0,G5000-26,multi-hop,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,The external technology provider named in Amazon's July AI-service expansion is Hugging Face. Alongside this partner...,"Amazon's July AI-service expansion named Hugging Face as the external technology provider. Additionally, it mentione...",1,1,1,1,1,1,2.019766,1.883875,842,1686,"The candidate incorrectly identifies Hugging Face as the external technology provider instead of Cohere, which is th...","The candidate incorrectly identifies Hugging Face as the external technology provider instead of Cohere, which is ex...",0
1,G5000-27,cross-doc,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,"The graph should illustrate that while AMD currently powers multiple cloud services, there is an ongoing evaluation ...","The graph indicates that AMD powers multiple cloud services, which suggests a strong presence in the cloud computing...",3,3,4,4,3,3,2.818724,2.573355,867,727,The candidate provides a reasonable explanation of the relationship between AMD's current role in powering cloud ser...,The candidate provides a reasonable explanation of how AMD's current role in powering cloud services can coexist wit...,0
2,G5000-28,multi-hop,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,The provided context does not specify any model providers connected to Google Cloud Next '23 or the models associate...,The model providers connected to Google Cloud Next '23 in the selected data are:\n\n1. **OpenAI**\n - Models assoc...,1,1,1,1,1,1,1.149410,3.412894,739,4481,The candidate fails to provide any information regarding the model providers connected to Google Cloud Next '23 or t...,The candidate fails to mention the correct model providers and their associated models as specified in the reference...,0
3,G5000-29,cross-doc,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",Participation in White House AI commitments broadened from July to September 2023 as additional tech companies joine...,Participation in White House AI commitments broadened from July to September 2023 as more tech companies joined the ...,4,4,5,5,4,4,5.145059,2.509622,821,671,The candidate provides a clear overview of the expansion of participation in White House AI commitments from July to...,The candidate provides a clear overview of the expansion of participation in White House AI commitments from July to...,0
4,G5000-30,multi-hop,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...","Meta appears in two distinct AI contexts:\n\n1. **Commitments on Managing AI**: In this context, Meta is one of the ...",Meta appears in two different AI contexts in the selected data:\n\n1. **Partnership with OpenAI**: Meta is noted as ...,2,1,3,1,2,1,3.072786,4.

In [47]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":("flat_comprehensiveness","graph_comprehensiveness"),
        "Faithfulness":("flat_faithfulness","graph_faithfulness"),
        "Multi-hop reasoning":("flat_multi_hop_reasoning","graph_multi_hop_reasoning"),
        "Latency (s)":("flat_latency_s","graph_latency_s"),
        "Token usage":("flat_total_tokens","graph_total_tokens"),
    }

    rows = []
    for group, g in eval_df.groupby("group"):
        for metric, (fc,gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)","Token usage"}:
                comment = "Flat RAG thường rẻ/nhanh hơn." if f < gr else "GraphRAG không đắt hơn trong sample này."
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cải thiện rõ; kiểm tra rationale và provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu."
                else:
                    comment = "Hai phương pháp gần nhau."

            rows.append({
                "Loại câu hỏi":group, "Metric":metric,
                "Flat RAG":round(f,3) if pd.notna(f) else np.nan,
                "GraphRAG":round(gr,3) if pd.notna(gr) else np.nan,
                "Nhận xét phân tích":comment
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)
os.makedirs("outputs", exist_ok=True)
eval_results_df.to_csv("outputs/graphrag_eval_results.csv", index=False)
comparison_df.to_csv("outputs/graphrag_vs_flatrag_summary.csv", index=False)

,Loại câu hỏi,Metric,Flat RAG,GraphRAG,Nhận xét phân tích
0,cross-doc,Comprehensiveness,2.091,2.273,Hai phương pháp gần nhau.
1,cross-doc,Faithfulness,2.455,2.818,Hai phương pháp gần nhau.
2,cross-doc,Multi-hop reasoning,2.000,2.182,Hai phương pháp gần nhau.
3,cross-doc,Latency (s),2.181,1.975,GraphRAG không đắt hơn trong sample này.
4,cross-doc,Token usage,784.636,1069.636,Flat RAG thường rẻ/nhanh hơn.
5,factoid,Comprehensiveness,2.500,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
6,factoid,Faithfulness,3.000,2.000,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
7,factoid,Multi-hop reasoning,2.500,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
8,factoid,Latency (s),1.223,1.113,GraphRAG không đắt hơn trong sample này.
9,factoid,Token usage,762.000,717.000,GraphRAG không đắt hơn trong sample này.


# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [42]:
#@title 5.1 — Super-node check + entity audit
def top_degree_nodes(limit=10):
    return run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT $limit
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    """, limit=int(limit))

def test_supernode_policy(stress_demo=True):
    rows = top_degree_nodes(10)
    if not rows:
        print("Graph empty.")
        return
    print("Top degree nodes:")
    display(pd.DataFrame(rows))

    n = rows[0]
    print(f"Production policy: SUPER_NODE_DEGREE={SUPER_NODE_DEGREE}, EDGE_CAP={SUPER_NODE_EDGE_CAP}")

    # Production path
    if n["degree"] > SUPER_NODE_DEGREE:
        edges = recent_edges(n["id"], SUPER_NODE_EDGE_CAP)
        print(n, "fetched=", len(edges))
        assert len(edges) <= SUPER_NODE_EDGE_CAP
        print("✅ Super-node cap OK (production threshold).")
        return

    print(
        f"Max degree={n['degree']} <= production threshold {SUPER_NODE_DEGREE} "
        "→ production cap not triggered on current graph."
    )

    # Lab stress-demo: chứng minh nhánh cắt tỉa vẫn chạy đúng khi hạ ngưỡng tạm
    if stress_demo and n["degree"] > LAB_SUPERNODE_STRESS_DEGREE:
        demo_limit = SUPER_NODE_EDGE_CAP
        edges = recent_edges(n["id"], demo_limit)
        print(
            f"Lab stress-demo (threshold={LAB_SUPERNODE_STRESS_DEGREE}): "
            f"{n['name']} degree={n['degree']} → fetch cap={demo_limit}, fetched={len(edges)}"
        )
        assert len(edges) <= SUPER_NODE_EDGE_CAP
        dbg = retrieve_graph_context(
            n["name"], return_debug=True, supernode_degree=LAB_SUPERNODE_STRESS_DEGREE
        )
        print("retrieve_graph_context stress supernode_events:", dbg["diagnostics"]["supernode_events"])
        print("✅ Super-node cap OK (lab stress-demo).")
    else:
        print(
            "Stress-demo skipped: tăng EXTRACTION_MAX_CHUNKS / hub stratification rồi re-ingest "
            "để có node degree cao hơn."
        )

def show_resolution_audit(audit_df, min_rows=10):
    if audit_df is None or audit_df.empty:
        print("No audit rows.")
        return
    display(audit_df.sort_values("similarity", ascending=False).head(30))
    print("Decision counts:")
    print(audit_df.decision.value_counts().to_string())
    print("High-similarity rejected pairs:")
    rejected = audit_df[audit_df.decision == "REJECT_GUARD"].sort_values("similarity", ascending=False)
    display(rejected.head(20))

    required = {"MERGE_MANUAL", "MERGE_VECTOR", "REJECT_GUARD"}
    present = set(audit_df.decision.unique())
    missing = required - present
    if len(audit_df) >= min_rows and not missing:
        print(f"✅ Entity resolution audit OK for rubric 2.3 (rows={len(audit_df)}).")
    else:
        print(
            f"⚠️ Audit chưa đủ rubric 2.3: rows={len(audit_df)} (need >={min_rows}), "
            f"missing_labels={missing or set()}."
        )
        print("Gợi ý: re-run extract với hub stratification + giữ threshold/guard hiện tại.")

test_supernode_policy()
show_resolution_audit(entity_resolution_audit_df)


Top degree nodes:


,id,name,type,degree
0,fb0f4df56fab164ec48722f0,Microsoft,Company,15
1,0e132222d1315530d6efca52,Google,Company,14
2,773eeb9b7cc008bff365fcdd,OpenAI,Company,12
3,e6c3db5c28c9a15bfafd2e04,Apple,Company,10
4,cc9c6ee3857729e221d3f6de,ServiceNow,Company,10
5,68b3544368862fc263941c8d,Amazon,Company,9
6,6dbfdfc5a4e8df3668a4dac3,Meta,Company,7
7,3669130c05135dd501f33457,technology,Technology,6
8,6d6d3bc05ca32388a48a053b,Truecaller,Company,5
9,eeef1b6e5ea6fc3be69da886,Tesla,Company,5


Production policy: SUPER_NODE_DEGREE=100, EDGE_CAP=50
Max degree=15 <= production threshold 100 → production cap not triggered on current graph.
Lab stress-demo (threshold=10): Microsoft degree=15 → fetch cap=50, fetched=15
retrieve_graph_context stress supernode_events: [{'node_id': 'fb0f4df56fab164ec48722f0', 'degree': 15, 'limit': 50, 'policy_degree': 10}]
✅ Super-node cap OK (lab stress-demo).


,type,left,right,similarity,decision
0,Company,ServiceNow Inc.,ServiceNow,1.000000,MERGE_MANUAL
1,Technology,AWS,Amazon,1.000000,MERGE_MANUAL
2,Company,Facebook,Meta,1.000000,MERGE_MANUAL
3,Company,Amazon.com,Amazon,1.000000,MERGE_MANUAL
4,Company,Apple Inc,Apple,1.000000,MERGE_MANUAL
5,Company,Meta Platforms,Meta,1.000000,MERGE_MANUAL
6,Company,Microsoft Corp.,Microsoft,1.000000,MERGE_MANUAL
7,Company,IBM Corp.,IBM,1.000000,MERGE_MANUAL
8,Company,Amazon Web Services Inc.,Amazon,1.000000,MERGE_MANUAL
9,Company,Meta Platforms Inc,Meta,1.000000,MERGE_MANUAL


Decision counts:
decision
MERGE_MANUAL    12
MERGE_VECTOR     7
REJECT_GUARD     4
High-similarity rejected pairs:


,type,left,right,similarity,decision
21,Technology,technology office,Office of Technology,0.931814,REJECT_GUARD
19,Technology,cloud-computing services,cloud computing,0.883056,REJECT_GUARD
22,Technology,identity proofing and passwordless multi-factor authentication,multi-factor passwordless authentication,0.865923,REJECT_GUARD
20,Technology,cloud-computing services,cloud services,0.864799,REJECT_GUARD


✅ Entity resolution audit OK for rubric 2.3 (rows=23).


In [43]:
entity_resolution_audit_df

,type,left,right,similarity,decision
0,Company,ServiceNow Inc.,ServiceNow,1.000000,MERGE_MANUAL
1,Technology,AWS,Amazon,1.000000,MERGE_MANUAL
2,Company,Facebook,Meta,1.000000,MERGE_MANUAL
3,Company,Amazon.com,Amazon,1.000000,MERGE_MANUAL
4,Company,Apple Inc,Apple,1.000000,MERGE_MANUAL
5,Company,Meta Platforms,Meta,1.000000,MERGE_MANUAL
6,Company,Microsoft Corp.,Microsoft,1.000000,MERGE_MANUAL
7,Company,IBM Corp.,IBM,1.000000,MERGE_MANUAL
8,Company,Amazon Web Services Inc.,Amazon,1.000000,MERGE_MANUAL
9,Company,Meta Platforms Inc,Meta,1.000000,MERGE_MANUAL


## 5.2 — Thuyết minh kỹ thuật

### 1. Coreference sai ở tình huống nào?
Tin HackerNoon thường nhắc nhiều công ty trong một đoạn (ví dụ: Amazon + đối tác AI). Đại từ hoặc cụm từ như `the company` dễ bị gắn nhầm sang thực thể gần nhất thay vì chủ thể sự kiện.

* **Hậu quả:** NER+RE tạo false edge (gán `PARTNERED_WITH` / `USES` sai công ty) $\rightarrow$ GraphRAG trả lời lệch dù traversal "có vẻ đúng".
* **Giải pháp:** Pipeline đã dùng conservative coref + `unresolved_mentions` để giảm rủi ro này.

---

### 2. Entity threshold bao nhiêu, vì sao?
`ENTITY_SIM_THRESHOLD = 0.85`, lexical guard `MERGE_GUARD_RATIO = 0.78`.

Ngưỡng `0.90` trước đó quá chặt (chỉ `~4 MERGE_VECTOR`, không có `REJECT_GUARD`). Hạ xuống `0.85` bắt được biến thể tên thật, đồng thời guard chặt hơn để không gộp false friend.

---

### 3. Candidate nào similarity cao nhưng không nên merge?
Từ file `outputs/entity_resolution_audit.csv`:

* **`technology office` vs `Office of Technology`** (sim `0.932`) $\rightarrow$ **REJECT_GUARD** (cùng từ vựng, khác thực thể/phạm vi).
* **`cloud-computing services` vs `cloud computing`** (sim `0.883`) $\rightarrow$ **Reject** (mô tả dịch vụ chung vs khái niệm chung, không đủ để gộp node).

---

### 4. Top 3 super-node và degree?
Theo **cell 5.1** (đồ thị sau re-ingest):

| Hạng | Tên | Type | Degree |
| :---: | :--- | :--- | :---: |
| **1** | Microsoft | Company | 15 |
| **2** | Google | Company | 14 |
| **3** | OpenAI | Company | 12 |

> Chưa node nào vượt ngưỡng production là 100. Hệ thống đã chứng minh khả năng capping bằng lab stress-demo (threshold = 10).

---

### 5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
* **Đúng:** Hub như Microsoft/Google có nhiều cạnh $\rightarrow$ lấy $\le 50$ cạnh `published_date` mới nhất giúp giảm nổ context, ưu tiên tin tức cập nhật.
* **Sai:** Với câu hỏi lịch sử/timeline (ví dụ: OpenAI March $\rightarrow$ July trong golden) có thể bị cắt mất cạnh cũ $\rightarrow$ mất thông tin multi-hop.

---

### 6. Flat RAG thắng nhóm nào?
**Factoid** — theo file `graphrag_vs_flatrag_summary.csv`: *Comprehensiveness* (2.5 vs 1.5), *Faithfulness* (3.0 vs 2.0).

* **Ví dụ (G5000-47 - Keysight–Synopsys / Palo Alto):** `flat_q` $\approx 4.33 >$ `graph_q` $\approx 2.33$.
* **Lý do:** Đây là câu hỏi xác nhận quan hệ đơn giản, vector chunk đã đủ; graph dễ gây nhiễu hoặc thiếu edge.

---

### 7. GraphRAG thắng nhóm nào?
**Cross-doc** (và một phần multi-hop): Chất lượng cross-doc của Graph cao hơn (*Faithfulness* 2.82 vs 2.46).

* **Ví dụ (G5000-37 - Dell NativeEdge May $\rightarrow$ July):** `flat_q` 1.0 vs `graph_q` $\approx 3.33$.
* **Lý do:** Cần nối nhiều bài/thời điểm khác nhau, graph traversal thể hiện ưu thế vượt trội hơn pure vector.

---

### 8. Latency/token trade-off?
Trên 25 câu eval:
* **Latency:** Gần tương đương nhau ($\sim 2.39$s Flat vs $\sim 2.37$s Graph).
* **Token:** GraphRAG dùng cao hơn rõ rệt ($\approx 1398$ vs $\approx 819$ overall; multi-hop $\approx 1813$ vs $\approx 859$).

$\rightarrow$ Graph không hẳn chậm hơn về wall-clock trong sample này, nhưng tốn chi phí context/token hơn. Flat rẻ hơn khi xử lý câu factoid đơn giản.

---

### 9. AI Coding Agent đề xuất gì mà bạn không dùng, vì sao?
* **Đề xuất của Agent:** Tính pairwise cosine $\mathcal{O}(N^2)$ cho toàn bộ entity, hoặc hạ `SUPER_NODE_DEGREE` production xuống 10 rồi im lặng coi là đủ rubric.
* **Từ chối vì:** 
  1. $\mathcal{O}(N^2)$ không thể scale và dễ gây OOM (Out of Memory).
  2. Hạ ngưỡng production sẽ che đi failure mode thực tế. Lab chọn cách dùng stress-demo tách bạch và giữ policy degree $> 100$.

---

### 10. Scale 350MB: bottleneck đầu tiên là gì?
**LLM Extraction (NER + RE + Coref)** — gặp hạn chế về chi phí, rate-limit và latency trước khi chạm ngưỡng giới hạn của Neo4j hay FAISS.

* **Hướng xử lý:**
  1. Batch/async queue processing.
  2. Chỉ extract subset + cập nhật theo dạng incremental (lũy tiến).
  3. ER bằng ANN + blocking (thay vì pairwise).
  4. Tạo community/global summary cho các câu hỏi vĩ mô.
  5. Giữ super-node cap + provenance trong quá trình retrieval.

# 🎁 BONUS

## A — Low-level / High-level
Near-Dedup (SimHash+LSH) đã chạy ở cell 1.5 → `outputs/near_dedup_audit.csv`.

## B — Global Search via Community Reports (+5)
1. Export edges từ Neo4j
2. NetworkX community detection (`greedy_modularity_communities`)
3. `UNWIND` ghi `community_id` lên node
4. LLM summarize mỗi community → community reports
5. Global search: rank reports theo embedding → generate answer

## C — Self-Correction Graph Retrieval (+5)
- Hop 2 → LLM kiểm tra context đủ chưa
- Thiếu → Hop 3
- Vẫn thiếu → vector fallback
- Stop condition bắt buộc (không vòng lặp vô hạn)


In [50]:
#@title Bonus B — Community detection + Global Search
import networkx as nx

COMMUNITY_SUMMARY_SYSTEM = """
You summarize a knowledge-graph community for global GraphRAG search.
Write 4-8 sentences covering: main entities, key relations/themes, and notable companies/technologies.
Do not invent facts beyond the supplied members and sample edges.
Return plain text only (no JSON).
""".strip()

def build_communities(limit_edges=20000):
    """Detect communities with NetworkX and write community_id back to Neo4j."""
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target, type(r) AS relation
    LIMIT $limit
    """, limit=int(limit_edges)))
    if edge_df.empty:
        raise RuntimeError("No edges in Neo4j — run bulk insert first.")

    G = nx.Graph()
    G.add_edges_from(edge_df[["source", "target"]].itertuples(index=False, name=None))
    communities = list(nx.algorithms.community.greedy_modularity_communities(G))

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id": node_id, "community_id": int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id: row.id})
        SET n.community_id = row.community_id
        """, rows=b)

    community_df = pd.DataFrame(rows)
    print(
        f"Communities={len(communities)} | labeled_nodes={len(community_df)} | "
        f"graph_nodes={G.number_of_nodes()} edges_used={len(edge_df)}"
    )
    return community_df, edge_df, communities


def _community_member_table(community_id, limit=40):
    return pd.DataFrame(run_cypher("""
    MATCH (n:Entity {community_id: $cid})
    RETURN n.id AS id, n.name AS name, n.entity_type AS type
    ORDER BY n.name
    LIMIT $limit
    """, cid=int(community_id), limit=int(limit)))


def _community_edge_samples(community_id, limit=25):
    return pd.DataFrame(run_cypher("""
    MATCH (a:Entity {community_id: $cid})-[r]->(b:Entity {community_id: $cid})
    RETURN a.name AS source, type(r) AS relation, b.name AS target,
           r.evidence AS evidence, r.published_date AS published_date
    ORDER BY coalesce(r.published_date, '') DESC
    LIMIT $limit
    """, cid=int(community_id), limit=int(limit)))


def summarize_community(community_id, max_members=35, max_edges=20):
    members = _community_member_table(community_id, limit=max_members)
    edges = _community_edge_samples(community_id, limit=max_edges)
    member_lines = [
        f"- {r.name} [{r.type}]" for r in members.itertuples(index=False)
    ]
    edge_lines = [
        f"- {r.source} -{r.relation}-> {r.target}"
        + (f" | {norm_space(r.evidence)[:160]}" if r.evidence else "")
        for r in edges.itertuples(index=False)
    ]
    prompt = f"""COMMUNITY_ID: {community_id}
MEMBERS ({len(members)} shown):
{chr(10).join(member_lines) if member_lines else '(none)'}

SAMPLE EDGES ({len(edges)} shown):
{chr(10).join(edge_lines) if edge_lines else '(none)'}

Write the community report now."""
    text, usage = llm_chat(
        [
            {"role": "system", "content": COMMUNITY_SUMMARY_SYSTEM},
            {"role": "user", "content": prompt},
        ],
        provider=GENERATE_PROVIDER,
        model=GENERATE_MODEL,
    )
    return {
        "community_id": int(community_id),
        "n_members": int(len(members)),
        "n_edge_samples": int(len(edges)),
        "top_entities": ", ".join(members["name"].head(12).tolist()) if len(members) else "",
        "report": norm_space(text),
        "total_tokens": usage.get("total_tokens"),
    }


def build_community_reports(community_df, min_size=3, max_communities=25):
    """Summarize largest communities and persist reports for global search."""
    sizes = (
        community_df.groupby("community_id").size()
        .sort_values(ascending=False)
        .reset_index(name="size")
    )
    sizes = sizes[sizes["size"] >= min_size].head(max_communities)
    reports = []
    for cid in tqdm(sizes["community_id"].tolist(), desc="Community reports"):
        try:
            reports.append(summarize_community(int(cid)))
        except Exception as e:
            reports.append({
                "community_id": int(cid),
                "n_members": int(sizes.loc[sizes.community_id == cid, "size"].iloc[0]),
                "n_edge_samples": 0,
                "top_entities": "",
                "report": f"[SUMMARY_FAILED] {e}",
                "total_tokens": None,
            })
    reports_df = pd.DataFrame(reports)
    reports_df.to_csv("outputs/community_reports.csv", index=False)
    print(f"Saved {len(reports_df)} community reports -> outputs/community_reports.csv")
    return reports_df


def _encode_reports(reports_df):
    texts = (
        reports_df["top_entities"].fillna("").astype(str) + "\n" +
        reports_df["report"].fillna("").astype(str)
    ).tolist()
    vecs = get_embedder().encode(
        texts, batch_size=32, show_progress_bar=False, normalize_embeddings=True
    ).astype("float32")
    index = faiss.IndexFlatIP(vecs.shape[1])
    index.add(vecs)
    return index, vecs


_community_report_index = None  # rebuilt in global_search / after reports build

def global_search(question, reports_df=None, top_k=3, return_debug=False):
    """Global GraphRAG: retrieve top community reports for macro questions."""
    global community_reports_df, _community_report_index
    if reports_df is None:
        reports_df = community_reports_df
    if reports_df is None or reports_df.empty:
        raise RuntimeError("community_reports_df empty — run build_community_reports first.")

    need_rebuild = (
        _community_report_index is None
        or getattr(_community_report_index, "ntotal", 0) != len(reports_df)
    )
    if need_rebuild:
        _community_report_index, _ = _encode_reports(reports_df)

    qv = get_embedder().encode(
        [question], normalize_embeddings=True
    ).astype("float32")
    k = min(int(top_k), len(reports_df))
    scores, idxs = _community_report_index.search(qv, k)
    hits = []
    for score, j in zip(scores[0], idxs[0]):
        if j < 0:
            continue
        row = reports_df.iloc[int(j)]
        hits.append({
            "community_id": int(row.community_id),
            "score": float(score),
            "top_entities": row.top_entities,
            "report": row.report,
        })
    context = "\n\n".join(
        f"[Community {h['community_id']} | score={h['score']:.3f}]\n"
        f"Entities: {h['top_entities']}\n{h['report']}"
        for h in hits
    )
    out = {"context": context, "hits": hits}
    return out if return_debug else context


def answer_global_rag(question, top_k=3):
    g = global_search(question, top_k=top_k, return_debug=True)
    out = generate_answer(question, g["context"])
    out.update({"mode": "global_community", "context": g["context"], "hits": g["hits"]})
    return out


# --- Run Bonus B ---
community_df, community_edge_df, communities = build_communities()
community_reports_df = build_community_reports(community_df, min_size=3, max_communities=20)
_community_report_index, _ = _encode_reports(community_reports_df)
display(community_reports_df[["community_id", "n_members", "top_entities", "report"]].head(5))

# Demo global questions (macro / overview style)
GLOBAL_DEMO_QUESTIONS = [
    "What major AI ecosystem themes and company clusters appear in this knowledge graph?",
    "Summarize how cloud providers and model vendors are connected across communities.",
]
global_demo_rows = []
for q in GLOBAL_DEMO_QUESTIONS:
    ans = answer_global_rag(q, top_k=3)
    global_demo_rows.append({
        "question": q,
        "answer": ans["answer"][:800],
        "latency_s": ans["latency_s"],
        "total_tokens": ans["total_tokens"],
        "hit_communities": ",".join(str(h["community_id"]) for h in ans["hits"]),
    })
    print("\nQ:", q)
    print("hits:", global_demo_rows[-1]["hit_communities"])
    print("A:", ans["answer"][:500], "...")

pd.DataFrame(global_demo_rows).to_csv("outputs/bonus_global_search_demo.csv", index=False)
print("Saved -> outputs/bonus_global_search_demo.csv")


Communities=300 | labeled_nodes=785 | graph_nodes=785 edges_used=504


Community reports: 100%|██████████| 20/20 [00:59<00:00,  2.99s/it]


Saved 20 community reports -> outputs/community_reports.csv


,community_id,n_members,top_entities,report
0,0,35,"AI technology, AirPods Pro, Alzheimer's disease diagnosis, Amazon, Amazon, Apple, Apple Business Connect, Apple H1 c...","The knowledge-graph community focuses on key entities in the technology and company sectors, particularly those invo..."
1,1,27,"AS/400, Accenture, Adobe, Deloitte, Former Intel employees, Gaming Laptops, Hua Zhu, Hywin, IBM, Intel, Jordan Digit...","The knowledge-graph community focuses on a diverse array of entities, primarily encompassing technology companies, n..."
2,2,21,"AI cloud services, Amazon.com Inc., ChatGPT, DEWA, Daragh Morrisey, Dynamics TMS®, HE Saeed Mohammed Al Tayer, KPMG,...","The knowledge-graph community focuses on the intersection of cloud computing, artificial intelligence, and technolog..."
3,3,18,"ARK Innovation ETF, Amazon Prime, Baird, California, Cathie Wood, Elon Musk, FIS, Fidelity National Information Serv...","The knowledge-graph community focuses on key entities in the technology and finance sectors, prominently featuring c..."
4,4,8,"1Kosmos, Beyond Identity, CyberArk, HYPR, NayaOne, Passwordless Authentication, Siddharth Gandhi, Transmit Security","The knowledge-graph community focuses on the domain of passwordless authentication, featuring key companies such as ..."



Q: What major AI ecosystem themes and company clusters appear in this knowledge graph?
hits: 2,7,0
A: The major AI ecosystem themes and company clusters identified in the knowledge graph include:

1. **Cloud Computing and AI Services**: This theme is prominent in Community 2, featuring key players like Microsoft and Amazon.com Inc., focusing on AI cloud services, custom silicon, and technology services. Partnerships, such as KPMG's collaboration with Microsoft, highlight corporate synergy in advancing cloud and AI capabilities.

2. **AI Supercomputing**: Community 7 emphasizes the development of ...

Q: Summarize how cloud providers and model vendors are connected across communities.
hits: 0,2,1
A: Cloud providers and model vendors are interconnected through a dynamic ecosystem characterized by collaboration and competition across various technology communities. Major players like Amazon, Microsoft, and Google are pivotal in developing and deploying AI and cloud computing services. Pa

In [51]:
#@title Bonus C — Self-Correction Graph Retrieval
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Prefer sufficient=false if key entities, relations, or dates are missing.
Return strict JSON only: {"sufficient": true|false, "missing": "..."}.
""".strip()

def context_sufficient(question, context):
    """LLM-as-sufficiency-check (uses GENERATE/EXTRACT provider via llm_json)."""
    if not norm_space(context):
        return False, "empty_context"
    obj, _ = llm_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return {{"sufficient": true, "missing": "..."}}""",
        provider=GENERATE_PROVIDER,
        model=GENERATE_MODEL,
    )
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))


def self_correcting_context(question, edge_limit=50, flat_k=8):
    """
    Hop2 -> (if insufficient) Hop3 -> (if still insufficient) Hop3+vector fallback.
    Hard stop after vector fallback (no further expansion).
    """
    trace = []

    g2 = retrieve_graph_context(question, max_hops=2, edge_limit=edge_limit, return_debug=True)
    ok, missing = context_sufficient(question, g2.get("context", ""))
    trace.append({"step": "hop2", "sufficient": ok, "missing": missing,
                  "n_edges": int(g2.get("diagnostics", {}).get("collected_edges", 0))})
    if ok:
        return {
            "route": "hop2",
            "context": g2["context"],
            "missing": "",
            "graph_debug": g2,
            "trace": trace,
            "stopped": True,
        }

    g3 = retrieve_graph_context(question, max_hops=3, edge_limit=edge_limit, return_debug=True)
    ok2, missing2 = context_sufficient(question, g3.get("context", ""))
    trace.append({"step": "hop3", "sufficient": ok2, "missing": missing2,
                  "n_edges": int(g3.get("diagnostics", {}).get("collected_edges", 0))})
    if ok2:
        return {
            "route": "hop3",
            "context": g3["context"],
            "missing": missing,
            "graph_debug": g3,
            "trace": trace,
            "stopped": True,
        }

    flat, vdocs = retrieve_flat_context(question, k=flat_k)
    merged = f"=== GRAPH (hop3) ===\n{g3.get('context','')}\n\n=== VECTOR FALLBACK ===\n{flat}"
    trace.append({"step": "vector_fallback", "sufficient": None, "missing": missing2,
                  "n_edges": int(g3.get("diagnostics", {}).get("collected_edges", 0))})
    return {
        "route": "hop3+vector",
        "context": merged,
        "missing": missing2,
        "graph_debug": g3,
        "vector_docs": vdocs,
        "trace": trace,
        "stopped": True,  # hard stop condition
    }


def answer_graph_rag_self_correct(question):
    """GraphRAG answer path with self-correction retrieval."""
    sc = self_correcting_context(question)
    out = generate_answer(question, sc["context"])
    out.update({
        "mode": "graph_self_correct",
        "route": sc["route"],
        "context": sc["context"],
        "missing": sc.get("missing"),
        "trace": sc.get("trace"),
        "graph_debug": sc.get("graph_debug"),
        "stopped": sc.get("stopped", True),
    })
    return out


# --- Demo / lightweight before-after on a few golden questions ---
SELF_CORRECT_DEMO_IDS = ["G5000-31", "G5000-34", "G5000-37", "G5000-44", "G5000-28"]

def _load_demo_questions(ids=SELF_CORRECT_DEMO_IDS):
    paths = [
        Path("data/graphrag_golden_50_first5000.csv"),
        Path("data/golden_dataset.csv"),
    ]
    # Prefer in-memory golden if present
    if "golden_df" in globals() and isinstance(golden_df, pd.DataFrame) and len(golden_df):
        df = golden_df.copy()
    else:
        df = None
        for p in paths:
            if p.exists():
                df = pd.read_csv(p)
                break
        if df is None:
            raise FileNotFoundError("No golden dataset found for self-correction demo.")
    id_col = "id" if "id" in df.columns else df.columns[0]
    q_col = "question" if "question" in df.columns else "query"
    sub = df[df[id_col].astype(str).isin(ids)].copy()
    if sub.empty:
        sub = df.head(5).copy()
    return sub, id_col, q_col


demo_df, id_col, q_col = _load_demo_questions()
self_correct_rows = []
for r in tqdm(list(demo_df.itertuples(index=False)), desc="Self-correct demo"):
    qid = getattr(r, id_col)
    question = getattr(r, q_col)
    # baseline hop2-only (no sufficiency loop)
    g2 = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    base = generate_answer(question, g2.get("context", ""))
    # self-correct
    sc_ans = answer_graph_rag_self_correct(question)
    self_correct_rows.append({
        "id": qid,
        "question": question,
        "baseline_route": "hop2",
        "baseline_answer": base["answer"][:600],
        "baseline_latency_s": base["latency_s"],
        "baseline_tokens": base["total_tokens"],
        "sc_route": sc_ans["route"],
        "sc_answer": sc_ans["answer"][:600],
        "sc_latency_s": sc_ans["latency_s"],
        "sc_tokens": sc_ans["total_tokens"],
        "sc_missing": sc_ans.get("missing"),
        "sc_trace": json.dumps(sc_ans.get("trace"), ensure_ascii=False),
    })
    print(f"{qid}: baseline=hop2 -> self_correct={sc_ans['route']}")

self_correct_demo_df = pd.DataFrame(self_correct_rows)
self_correct_demo_df.to_csv("outputs/bonus_self_correction_demo.csv", index=False)
print("Route distribution:")
print(self_correct_demo_df["sc_route"].value_counts().to_string())
print("Saved -> outputs/bonus_self_correction_demo.csv")
display(self_correct_demo_df[["id", "baseline_route", "sc_route", "sc_latency_s", "sc_tokens"]])


Self-correct demo:  20%|██        | 1/5 [00:39<02:37, 39.37s/it]

G5000-28: baseline=hop2 -> self_correct=hop3+vector


Self-correct demo:  40%|████      | 2/5 [01:06<01:35, 31.98s/it]

G5000-31: baseline=hop2 -> self_correct=hop3+vector


Self-correct demo:  60%|██████    | 3/5 [01:24<00:51, 25.53s/it]

G5000-34: baseline=hop2 -> self_correct=hop3+vector


Self-correct demo:  80%|████████  | 4/5 [01:29<00:17, 17.69s/it]

G5000-37: baseline=hop2 -> self_correct=hop3+vector


Self-correct demo: 100%|██████████| 5/5 [01:41<00:00, 20.21s/it]

G5000-44: baseline=hop2 -> self_correct=hop3+vector
Route distribution:
sc_route
hop3+vector    5
Saved -> outputs/bonus_self_correction_demo.csv


,id,baseline_route,sc_route,sc_latency_s,sc_tokens
0,G5000-28,hop2,hop3+vector,1.620979,4863
1,G5000-31,hop2,hop3+vector,4.147836,5136
2,G5000-34,hop2,hop3+vector,4.045361,4267
3,G5000-37,hop2,hop3+vector,1.653263,1014
4,G5000-44,hop2,hop3+vector,1.720328,1106


### Bonus B/C — Cách chạy
1. Đảm bảo Neo4j đã có graph (cell 2.3) + Flat index (cell 3.x) + `generate_answer` đã định nghĩa.
2. Chạy **Bonus B** (community + reports + global demo) → `outputs/community_reports.csv`, `outputs/bonus_global_search_demo.csv`.
3. Chạy **Bonus C** (self-correction demo) → `outputs/bonus_self_correction_demo.csv`.
4. Ghi vào `reports/lab_report.md`: số community, ví dụ global answer, phân bố route hop2/hop3/hop3+vector.


# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [✅] Neo4j connected
- [✅] Dedup/chunking đã chạy
- [✅] Coreference spot-check
- [✅] Entity resolution audit
- [✅] `UNWIND` bulk insert
- [✅] 0 edge thiếu provenance
- [✅] Flat RAG chạy
- [✅] GraphRAG chạy
- [✅] Super-node check
- [✅] Golden Dataset có gold answers thật
- [✅] Evaluation chạy hết
- [✅] Export results + summary CSV
- [✅] Thuyết minh kỹ thuật
- [✅] Bonus Near-Dedup audit CSV
- [✅] Bonus B: community_reports.csv + global demo
- [✅] Bonus C: self_correction demo (route hop2/hop3/vector)
